services:
  - type: web
    name: cognitive-test-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      flask init-db
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5 # 사용하시는 파이썬 버전에 맞게 수정 가능