services:
  - type: web
    name: cognitive-test-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "--- 현재 파일 목록 ---"
      ls -R
      echo "--- 마이그레이션 시작 ---"
      flask db upgrade
      echo "--- 마이그레이션 완료 ---"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # 안정적인 버전으로 수정
      - key: SECRET_KEY # 예시, Render 대시보드에서 실제 값 설정
        generateValue: true
      - key: ADMIN_PASSWORD # 예시, Render 대시보드에서 실제 값 설정
        value: "your_secure_password"